# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-13 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ViewerPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_user_id', models.IntegerField(default=0)),
                ('v_permission_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ViewerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_username', models.CharField(max_length=32, unique=True)),
                ('v_password', models.CharField(max_length=256)),
            ],
        ),
    ]
