# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-11 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=32, unique=True)),
                ('p_users', models.ManyToManyField(to='Admin.AdminUser')),
            ],
        ),
    ]
