# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-12 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0003_movie_m_price'),
        ('Cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaMovieOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_status', models.IntegerField(default=0)),
                ('c_price', models.FloatField(default=0)),
                ('c_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Common.Movie')),
                ('c_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cinema.CinemaUser')),
            ],
        ),
    ]
