# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-12 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema', '0002_cinemamovieorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemamovieorder',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
