# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-14 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema', '0006_paidang'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidang',
            name='p_time_end',
            field=models.DateTimeField(default='2018-12-13 02:00:00'),
        ),
    ]
