# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-11 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='m_open_day',
            field=models.DateTimeField(default='1970-1-1 00:00:00'),
        ),
    ]
